name: Update IPs and Create Release

on:
  workflow_dispatch:

jobs:
  update-ips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        pip install packaging

    - name: Run update script
      id: run_update_script
      run: |
        python ./automation_scripts/init.py --config ./automation_scripts/input.json
      env: 
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Run Azure CLI command
      run: |
        bash ./automation_scripts/az_ip_update.sh